[supervisord]
nodaemon=true

[program:xvfb]
command=/usr/bin/Xvfb :1 -screen 0 1366x768x16 -nolisten tcp
priority=10
autorestart=true
startretries=3
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr

[program:openbox]
command=/bin/bash -lc "DISPLAY=:1 openbox-session"
user=app
priority=20
autorestart=true
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr

[program:x11vnc]
command=/bin/bash -lc "x11vnc -display :1 -rfbport 5901 -forever -shared -nopw -noxdamage -ncache 10 -bg -o /dev/stdout"
priority=30
autorestart=true
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr

[program:websockify]
command=/bin/bash -lc "websockify --web=/opt/novnc 8080 localhost:5901"
priority=40
autorestart=true
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr

[program:desktop-init]
command=/start.sh
priority=50
autorestart=false
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
